// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYyRNhOVXKKzL8eqPHl356ZZevBa1077Y',
    appId: '1:768090443519:web:55a4387a240c31d20746ca',
    messagingSenderId: '768090443519',
    projectId: 'lab8-76e11',
    authDomain: 'lab8-76e11.firebaseapp.com',
    storageBucket: 'lab8-76e11.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJD7j2zaDnhw0Vp-peTmpMox23QRy1bIM',
    appId: '1:832984180704:android:fa172f8586404c0181ed85',
    messagingSenderId: '832984180704',
    projectId: 'fire-a31d5',
    storageBucket: 'fire-a31d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt0m49gOdqmVGPbJxDL2JaIgMySa4TaBY',
    appId: '1:832984180704:ios:9b02a45de1a72c5081ed85',
    messagingSenderId: '832984180704',
    projectId: 'fire-a31d5',
    storageBucket: 'fire-a31d5.appspot.com',
    iosBundleId: 'com.example.expensetracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt0m49gOdqmVGPbJxDL2JaIgMySa4TaBY',
    appId: '1:832984180704:ios:9b02a45de1a72c5081ed85',
    messagingSenderId: '832984180704',
    projectId: 'fire-a31d5',
    storageBucket: 'fire-a31d5.appspot.com',
    iosBundleId: 'com.example.expensetracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDG4bnRIzeoY2GTaAEJYLzP1_ftVmR_qc4',
    appId: '1:832984180704:web:c229d5d52cd5d35d81ed85',
    messagingSenderId: '832984180704',
    projectId: 'fire-a31d5',
    authDomain: 'fire-a31d5.firebaseapp.com',
    storageBucket: 'fire-a31d5.appspot.com',
  );
}